name: MUR Build
on: [push, pull_request]
jobs:
  build:
    name: ${{ matrix.arduino-boards-fqbn }} - Arduino Compilation
    runs-on: ubuntu-latest
    env:
      REQUIRED_LIBRARIES: Adafruit NeoPixel,Servo, Adafruit BME280
    strategy:
      matrix:
        arduino-boards-fqbn:
          - arduino:avr:mega
          - arduino:avr:uno
          - esp8266:esp8266:huzzah:eesz=4M3M,xtal=80

        include:
          - arduino-boards-fqbn: arduino:avr:mega
            sketch-names: "**.ino" # Comma separated list of sketch names (no path required) or patterns to use in build
            examples-build-properties:
              MUR:
                -DDEBUG
              MURTest:
                -DINFO

          - arduino-boards-fqbn: arduino:avr:uno # UNO board with different build properties
            examples-exclude: MURTest # Comma separated list of (unique substrings of) example names to exclude in build
            examples-build-properties:
              MUR:
                -DDEBUG
                -DTRACE

          - arduino-boards-fqbn: esp8266:esp8266:huzzah:eesz=4M3M,xtal=80
            platform-url: https://arduino.esp8266.com/stable/package_esp8266com_index.json
            examples-exclude: MURTest          

      fail-fast: false
      steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Compile all examples
        uses: ArminJo/arduino-test-compile@v2.0.0
        with:
          arduino-board-fqbn: ${{ matrix.arduino-boards-fqbn }}
          platform-url: ${{ matrix.platform-url }}
          required-libraries: ${{ env.REQUIRED_LIBRARIES }}
          examples-exclude: ${{ matrix.examples-exclude }}
          examples-build-properties: ${{ toJson(matrix.examples-build-properties) }}
