name: MUR Build
on: [push, pull_request]
jobs:
  build:
    name: Compiling sketch for Arduino
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Compile all examples
      uses: ArminJo/arduino-test-compile@v2.0.0
      with:
        arduino-board-fqbn: arduino:avr:mega
        sketch-names: "**.ino" 
        required-libraries: Servo,Wire,"Adafruit BME280 Library"
